export type MissionStep = {
  title: string;
  description: string;
  type: "action" | "reflection" | "discovery";
};

export type ExploreMission = {
  id: string;
  name: string;
  category: string;
  tab: string;
  description: string;
  longDescription: string;
  matchScore: number;
  reward: string;
  points: number;
  participants: number;
  location: string;
  verified: boolean;
  due: string;
  color: string;
  image: string;
  skills: string[];
  steps: MissionStep[];
  organiser: string;
  organiserType: string;
};

export const MISSION_COLOR_MAP: Record<string, string> = {
  energy:  "var(--color-energy)",
  reward:  "var(--color-reward)",
  primary: "var(--primary)",
  rose:    "var(--color-rose)",
  ai:      "var(--color-ai)",
  sky:     "var(--color-sky)",
};

export const exploreMissions: ExploreMission[] = [
  {
    id: "m1",
    name: "Climate Action Sprint",
    category: "Sustainability",
    tab: "Community",
    description: "Join local teams organising beach and park clean-up events. Submit photo evidence to earn points.",
    longDescription: "Work with your local community to organise or participate in environmental clean-up events. Take photos, submit a short field report, and earn a verified sustainability badge. All proof is checked by our community reviewers before points are awarded.",
    matchScore: 97,
    reward: "200 pts + badge",
    points: 200,
    participants: 412,
    location: "London, UK",
    verified: true,
    due: "3 days left",
    color: "primary",
    image: "photo-1569163139599-0f4517e36f51",
    skills: ["Volunteering", "Sustainability"],
    organiser: "GreenCity Network",
    organiserType: "NGO",
    steps: [
      { title: "Find an event near you", description: "Browse scheduled clean-up events in your area or register your own.", type: "discovery" },
      { title: "Attend and participate", description: "Show up, take part, and help coordinate your local group.", type: "action" },
      { title: "Submit your proof", description: "Upload 3+ photos of your work. Include a before-and-after if possible.", type: "action" },
      { title: "Share your impact", description: "Write one sentence about what your team achieved. This goes on your public record.", type: "reflection" },
    ],
  },
  {
    id: "m2",
    name: "Resilient Cities Research",
    category: "Research",
    tab: "Remote",
    description: "Contribute to citizen science research on urban resilience. Surveys and field reporting.",
    longDescription: "Help researchers understand how cities can better withstand climate stress, infrastructure strain, and population growth. Complete structured surveys, document local observations, and contribute to a dataset that feeds into real policy work.",
    matchScore: 94,
    reward: "250 pts + certificate",
    points: 250,
    participants: 42,
    location: "Remote",
    verified: true,
    due: "7 days left",
    color: "ai",
    image: "photo-1532187863486-abf9dbad1b69",
    skills: ["Analysis", "Reporting"],
    organiser: "Urban Futures Lab",
    organiserType: "Research Institution",
    steps: [
      { title: "Complete the baseline survey", description: "Answer 20 questions about your local area's infrastructure, green space, and community resilience.", type: "action" },
      { title: "Document 3 local observations", description: "Take photos or notes of infrastructure, public spaces, or community resources in your area.", type: "discovery" },
      { title: "Submit your field report", description: "Write a 200-word summary of what you observed and any patterns you noticed.", type: "reflection" },
      { title: "Peer review one other report", description: "Review and rate a report from another participant to earn your certificate.", type: "action" },
    ],
  },
  {
    id: "m3",
    name: "Workforce Readiness Programme",
    category: "Workforce Development",
    tab: "Learning",
    description: "Complete career skill modules, earn a verified certificate, and get matched to employers.",
    longDescription: "A structured programme to help you build the skills employers are looking for. Complete online modules, practice real-world tasks, and earn a verifiable certificate that goes on your X-Hunt profile. Participating employers actively recruit from this programme.",
    matchScore: 93,
    reward: "180 pts + badge",
    points: 180,
    participants: 128,
    location: "Remote",
    verified: true,
    due: "14 days left",
    color: "sky",
    image: "photo-1521791136064-7986c2920216",
    skills: ["Mentorship", "Communication"],
    organiser: "Skills Forward UK",
    organiserType: "Training Provider",
    steps: [
      { title: "Complete the skills assessment", description: "A 15-minute self-assessment to identify your strongest skills and growth areas.", type: "discovery" },
      { title: "Finish 3 skill modules", description: "Choose from communication, project management, digital literacy, or teamwork.", type: "action" },
      { title: "Complete a practice task", description: "Apply one skill in a structured scenario reviewed by a mentor.", type: "action" },
      { title: "Earn your certificate", description: "Pass the final assessment with a score of 70% or above.", type: "action" },
    ],
  },
  {
    id: "m4",
    name: "Urban Biodiversity Survey",
    category: "Exploration",
    tab: "Nearby",
    description: "Map and photograph local green spaces, parks, and wildlife habitats. GPS logs required.",
    longDescription: "Help build the UK's most comprehensive map of urban wildlife habitats. Walk your local parks, gardens, and green corridors. Photograph what you find. Your GPS-tagged submissions feed into city planning and conservation databases used by councils and research institutes.",
    matchScore: 88,
    reward: "160 pts",
    points: 160,
    participants: 67,
    location: "Nearby",
    verified: false,
    due: "5 days left",
    color: "reward",
    image: "photo-1476514525535-07fb3b4ae5f1",
    skills: ["Field Research", "Photography"],
    organiser: "Wildspace Trust",
    organiserType: "Conservation Charity",
    steps: [
      { title: "Download the survey guide", description: "Get the simple 1-page field guide that tells you what to look for.", type: "discovery" },
      { title: "Visit 2 green spaces", description: "Any park, garden, riverbank, or green corridor counts. Enable GPS.", type: "action" },
      { title: "Submit 5+ tagged photos", description: "Photograph plants, birds, insects, or habitats. GPS coordinates required.", type: "action" },
      { title: "Log your observations", description: "Use the simple observation form to record what you found at each location.", type: "reflection" },
    ],
  },
  {
    id: "m5",
    name: "Community Learning Hub",
    category: "Learning & Education",
    tab: "Learning",
    description: "Run or attend local skill-sharing workshops. Attendance records verify your contribution.",
    longDescription: "Organise or join skill-sharing sessions in your community. Anything from cooking to coding to gardening counts — as long as you show up and contribute. Attendance is verified by the host. Run your own session and earn bonus points for teaching.",
    matchScore: 91,
    reward: "240 pts",
    points: 240,
    participants: 84,
    location: "Manchester, UK",
    verified: true,
    due: "10 days left",
    color: "sky",
    image: "photo-1434030216411-0b793f4b6f57",
    skills: ["Teaching", "Community"],
    organiser: "Manchester Learning Collective",
    organiserType: "Community Group",
    steps: [
      { title: "Sign up for a session", description: "Browse upcoming workshops and register your spot (or list your own).", type: "discovery" },
      { title: "Attend the session", description: "Turn up and participate. The host will mark your attendance on the app.", type: "action" },
      { title: "Share one thing you learned", description: "Post a brief takeaway to the mission feed — helps others learn too.", type: "reflection" },
      { title: "Bonus: host your own session", description: "Lead a 30-minute skill session to earn an extra 80 points.", type: "action" },
    ],
  },
  {
    id: "m6",
    name: "Neighbourhood Improvement Drive",
    category: "Community Impact",
    tab: "Community",
    description: "Volunteer for local improvement projects — parks, schools, and community spaces.",
    longDescription: "Join volunteer teams making real improvements to local parks, schools, community centres, and public spaces. No experience needed — just show up and help out. Projects are verified by community coordinators and your time is logged on your profile.",
    matchScore: 86,
    reward: "120 pts",
    points: 120,
    participants: 203,
    location: "Birmingham, UK",
    verified: true,
    due: "Open-ended",
    color: "rose",
    image: "photo-1531206715517-5c0ba140b2b4",
    skills: ["Volunteering", "Leadership"],
    organiser: "Birmingham Council",
    organiserType: "Local Authority",
    steps: [
      { title: "Choose a project", description: "Browse active projects near you — park restoration, school garden, mural painting, and more.", type: "discovery" },
      { title: "Sign up for a volunteer slot", description: "Pick a date and time that works. Slots are usually 2–4 hours.", type: "action" },
      { title: "Complete your volunteer shift", description: "Show up, sign in with the coordinator, and do the work.", type: "action" },
      { title: "Log your hours", description: "Your coordinator verifies your attendance. Your hours are added to your record.", type: "reflection" },
    ],
  },
  {
    id: "m7",
    name: "Employee Wellness Challenge",
    category: "Health & Wellness",
    tab: "Remote",
    description: "10,000 steps a day for 30 days. Log your activity and earn a verified health record.",
    longDescription: "Build a healthier daily routine alongside your colleagues. Hit 10,000 steps a day for 30 days. Connect your fitness tracker or log manually. Weekly check-ins keep you accountable and the community leaderboard makes it fun. Employers use this data to demonstrate workforce wellbeing investment.",
    matchScore: 82,
    reward: "150 pts",
    points: 150,
    participants: 318,
    location: "Remote",
    verified: true,
    due: "Ongoing",
    color: "energy",
    image: "photo-1571019613454-1cb2f99b2d8b",
    skills: ["Health", "Accountability"],
    organiser: "Wellbeing at Work Collective",
    organiserType: "Corporate Programme",
    steps: [
      { title: "Set your baseline", description: "Log your current daily step average. Honesty is rewarded — this is your personal benchmark.", type: "reflection" },
      { title: "Hit 10,000 steps daily", description: "Any method counts — walking, running, cycling equivalents. Connect a tracker or log manually.", type: "action" },
      { title: "Complete 4 weekly check-ins", description: "Share a quick update each Friday — what's working, what's challenging.", type: "reflection" },
      { title: "Finish the 30-day programme", description: "Complete all 30 days with at least 25 qualifying days to earn your verified health record.", type: "action" },
    ],
  },
  {
    id: "m8",
    name: "AI Ethics Audit Sprint",
    category: "Research",
    tab: "Remote",
    description: "Review AI decision logs and flag potential bias issues. Structured review process with guidance.",
    longDescription: "Help make AI fairer. You'll be given real (anonymised) AI decision logs and structured review criteria. Flag potential bias, document your reasoning, and submit your findings. No technical background required — we provide full guidance and your reviews are checked by an expert panel.",
    matchScore: 79,
    reward: "300 pts + certificate",
    points: 300,
    participants: 33,
    location: "Remote",
    verified: true,
    due: "21 days left",
    color: "ai",
    image: "photo-1485827404703-89b55fcc595e",
    skills: ["Analysis", "Ethics"],
    organiser: "AI Fairness Initiative",
    organiserType: "Research Collective",
    steps: [
      { title: "Complete the training module", description: "A 30-minute guide on AI bias types and how to spot them. No prior knowledge needed.", type: "discovery" },
      { title: "Review 5 decision logs", description: "You'll receive 5 anonymised AI decision records. Flag any patterns that concern you.", type: "action" },
      { title: "Document your reasoning", description: "For each flag, write 2–3 sentences explaining what you noticed and why it matters.", type: "reflection" },
      { title: "Submit and get verified", description: "Expert panel reviews your audit within 5 days. Approved audits earn the certificate.", type: "action" },
    ],
  },
  {
    id: "m9",
    name: "Creator Skill Guild",
    category: "Learning & Education",
    tab: "Learning",
    description: "Level up your creative skills — design, writing, video. Peer-reviewed output earns attribution.",
    longDescription: "A peer-learning community for creatives. Choose a skill — graphic design, copywriting, video editing, photography, or illustration — complete structured exercises, and share your work for peer review. Reviewed work gets added to your verified portfolio.",
    matchScore: 84,
    reward: "85 pts + portfolio entry",
    points: 85,
    participants: 156,
    location: "Remote",
    verified: false,
    due: "Ongoing",
    color: "sky",
    image: "photo-1561070791-2526d30994b5",
    skills: ["Design", "Writing"],
    organiser: "Creator Commons",
    organiserType: "Community Guild",
    steps: [
      { title: "Choose your creative skill", description: "Pick one: design, writing, video, photography, or illustration.", type: "discovery" },
      { title: "Complete the weekly exercise", description: "A focused creative brief. Takes 2–4 hours. All levels welcome.", type: "action" },
      { title: "Share your work", description: "Post your completed work to the guild feed for peer review.", type: "action" },
      { title: "Review 2 other members' work", description: "Give structured feedback on two submissions. Good reviews earn you reputation too.", type: "reflection" },
    ],
  },
];
